# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build and Deploy at firebase

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    
    env:
      REACT_APP_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      REACT_APP_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      REACT_APP_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
      REACT_APP_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      REACT_APP_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      REACT_APP_MSG_ID: ${{ secrets.FIREBASE_MESSAGE_ID }}
      REACT_APP_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Firebase Deploy
        run: |
          sudo npm install -g firebase-tools
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting
